FROM php:7.4

RUN apt-get update -y && apt-get install -y openssl zip unzip git libonig-dev cron libicu-dev
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo mbstring mysqli pdo_mysql intl
RUN pecl install -o -f redis \
&&  rm -rf /tmp/pear \
&&  docker-php-ext-enable redis

WORKDIR /app/
COPY . /app/
RUN composer install
RUN php artisan config:clear \
    && composer dump-autoload \
    && php artisan route:clear \
    && php artisan view:clear

COPY docker/crontab /etc/cron.d/cron
RUN chmod 0644 /etc/cron.d/cron
RUN crontab /etc/cron.d/cron

CMD ["cron", "-f"]
